# Variables
@baseUrl = http://localhost:3333

# Health
GET {{baseUrl}}/health

###

# Get Rooms
GET {{baseUrl}}/rooms

###

# Post Rooms
POST {{baseUrl}}/rooms
Accept: : application/json
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Essa é uma sala de teste"
}